### ISSUE TITLE
User Tooling: Unit Tests and Integration Tests

### ISSUE THREAD

**Issue by Kelerchian** [Actyx/machines#18]
Stories:
- As a user, I want to test my MachineRunner-facing code, so that I check if my code is correct. 
- As a user, I want to test my system that involves MachineRunner-facing code, so that I can verify if the overall system works correctly.

Acceptance Criteria:
- Toolings are provided to fulfill the above stories.
- Toolings can come in the form of APIs, user manual, example code, etc

**Comment by rkuhn** [comment]
As a first step this issue will need to be updated with a list of concerns to be covered, so that we can assess the scope of the implementation.

**Comment by Kelerchian** [comment]
> list of concerns to be covered

I will need to look for use-cases

**Comment by Kelerchian** [comment]
I picture two cases that needs testing:

- The first one is that the user needs to verify commands and reactions that they write regardless of actyx. A simpler version of Runner in runner.test.ts is sufficient for this.
- The second one is to simulate the swarm (different machines) in one environment.

The second one is still pretty vague to me, but the first one is easy enough to implement

**Comment by rkuhn** [comment]
We should be more precise: could you sketch the kind of code a user would write for unit testing a given machine?

Integration tests will be quite different from unit tests (e.g. async vs sync), so we should probably split up this issue in two parts.

**Comment by Kelerchian** [comment]
Sure. Will do. I'll do add a the mockup utils too for the sync test
