### ISSUE TITLE
createMachineRunner parameters type bug in the declaration file

### ISSUE THREAD

**Issue by Kelerchian** [Actyx/machines#37]
- In the declaration file resulting from compilation, the `createMachineRunner` function's tags parameters are faulty (see below).
- `Reduce` code is expanded incorrectly by the typescript compiler.
- The root cause of the expansion is not yet found. 
- A quick investigation reveals that it only happens in parameter type and nowhere else.
- It is most likely a bug in the typescript compiler. Although no related issue in the TypeScript repository is found yet that we can link to.

Tasks
- [ ] As a workaround, downgrade the type requirements in the meantime so that it is more lenient
- [ ] Write type checks.
- [ ] Launch a separate investigation for why and when this phenomenon happens so that in the future we can catch it early.
- [ ] Attempt proper fix to restore the type requirements

```
export declare const createMachineRunner: <
  SwarmProtocolName extends string,
  MachineName extends string,
  RegisteredEventsFactoriesTuple extends readonly MachineEvent.Factory.Any[],
  Payload,
>(
  sdk: Actyx,
  tags: Tags<
    RegisteredEventsFactoriesTuple extends readonly [
      MachineEvent.Factory<infer Key extends string, infer Payload_1 extends object>,
      ...infer Rest,
    ]
      ? Rest extends readonly [
          MachineEvent.Factory<infer Key extends string, infer Payload_1 extends object>,
          ...infer Rest,
        ]
        ? Rest extends readonly [
            MachineEvent.Factory<infer Key extends string, infer Payload_1 extends object>,
            ...infer Rest,
          ]
          ? Rest extends readonly [
              MachineEvent.Factory<infer Key extends string, infer Payload_1 extends object>,
              ...infer Rest,
            ]
            ? Rest extends readonly [
                MachineEvent.Factory<infer Key extends string, infer Payload_1 extends object>,
                ...infer Rest,
              ]
              ? Rest extends readonly [
                  MachineEvent.Factory<infer Key extends string, infer Payload_1 extends object>,
                  ...infer Rest,
                ]
                ? Rest extends readonly [
                    MachineEvent.Factory<infer Key extends string, infer Payload_1 extends object>,
                    ...infer Rest,
                  ]
                  ? Rest extends readonly [
                      MachineEvent.Factory<
                        infer Key extends string,
                        infer Payload_1 extends object
                      >,
                      ...infer Rest,
                    ]
                    ? Rest extends readonly [
                        MachineEvent.Factory<
                          infer Key extends string,
                          infer Payload_1 extends object
                        >,
                        ...infer Rest,
                      ]
                      ? Rest extends readonly [
                          MachineEvent.Factory<
                            infer Key extends string,
                            infer Payload_1 extends object
                          >,
                          ...infer Rest,
                        ]
                        ? Rest extends readonly [
                            MachineEvent.Factory<
                              infer Key extends string,
                              infer Payload_1 extends object
                            >,
                            ...infer Rest,
                          ]
                          ? any
                          : MachineEvent<Key, Payload_1>
                        : MachineEvent<Key, Payload_1>
                      : MachineEvent<Key, Payload_1>
                    : MachineEvent<Key, Payload_1>
                  : MachineEvent<Key, Payload_1>
                : MachineEvent<Key, Payload_1>
              : MachineEvent<Key, Payload_1>
            : MachineEvent<Key, Payload_1>
          : MachineEvent<Key, Payload_1>
        : MachineEvent<Key, Payload_1>
      : never
  >,
  initialFactory: StateFactory<
    SwarmProtocolName,
    MachineName,
    RegisteredEventsFactoriesTuple,
    any,
    Payload,
    any
  >,
  initialPayload: Payload,
) => MachineRunner<SwarmProtocolName, MachineName>
```

**Comment by rkuhn** [comment]
Could you try adding one more type parameter so that the argument becomes `tags: Tags`? Perhaps that way the expansion is stopped?

**Comment by Kelerchian** [comment]
The same thing happens. `.Reduce` gets expanded inside the outermost `<>`.
I've also tried:
- Creating another function that only receives 1 param: `Reduce<Factories>` (happens here too)
- Removing `never` from LooseReduceToEvent

Also found that the issue also happens in `src/test-utils/mock-runner`. The Subscription.make function

**Comment by rkuhn** [comment]
One more idea: compute the reduction upon `SwarmProtocol.make()` already.

**Comment by Kelerchian** [comment]
> One more idea: compute the reduction upon `SwarmProtocol.make()` already.

I project that there will be issues:
- EventFactories are required by StateFactory, to match against the reaction's event chains and commands (so EventFactories can't be removed)
- Derived/calculated types calculated in different places can sometimes mismatch each other despite being written from exactly the same source.

I will try this approach and some other alternatives that crosses my mind. I added one more checklist item above to reach a proper fix. But I'll do it after writing the github actions.

**Comment by Kelerchian** [comment]
The idea is to use this instead of `Reduce`.
![image](https://user-images.githubusercontent.com/11693412/234275202-bf56f2d6-793a-4381-9409-fb4fc071d1ac.png)
