### ISSUE TITLE
[machine-check] Unreachable Nodes Not Verified

### ISSUE THREAD

**Issue by Kelerchian** [Actyx/machines#65]
`machine-check` should check for unreachable nodes in a swarm protocol.
There does not seem to be any reason a state is unreachable in a `machine-runner` workflow.

### Example

Run the code below, `checkSwarmProtocol` returns { "type": "OK" }.

```typescript
const swarmProtocol: SwarmProtocolType = {
  initial: "Initial",
  transitions: [
    {
      source: "Initial",
      target: "Docking",
      label: { cmd: "dockAvailable", role: "pump", logType: [ProtocolEvents.DockAvailable.type], },
    },
    // {
    //   source: "Docking",
    //   target: "DockedAndWaitingForWater",
    //   label: { cmd: "docked", role: "robot", logType: [ProtocolEvents.RobotIsDocked.type], },
    // },
    {
      source: "DockedAndWaitingForWater",
      target: "WaterDrawn",
      label: { cmd: "waterSupplied", role: "pump", logType: [ProtocolEvents.WaterSupplied.type], },
    },
    {
      source: "WaterDrawn",
      target: "Undocked",
      label: { cmd: "undocked", role: "robot", logType: [ProtocolEvents.RobotIsUndocked.type], },
    },
  ],
};

const subscriptions = {
  pump: [ 'DockAvailable', 'WaterSupplied', 'RobotIsUndocked' ],
  robot: [ 'DockAvailable', 'WaterSupplied', 'RobotIsUndocked' ]
};

checkSwarmProtocol(swarmProtocol, subscriptions)
```

**Comment by rkuhn** [comment]
For the underlying theory unreachable states are irrelevant. I agree that flagging such states in machine-check is a good idea because it likely points towards unintended machine behaviour — why write down states that are useless?

**Comment by Kelerchian** [comment]
> why write down states that are useless?

It is not that useless states are intentional. `machine-check` does 
`SwarmProtocolType` itself is a list of `transitions` where `states` are the set from the transitions `sources` and `targets`.
The users don't experience a phase where they need to explicitly list the states, and thus they don't have the "workspace" to review them either.
This will increase the users' chance to make mistakes, further made severe by the fact that the states are arbitrary strings.
So this flagging of unreachable states helps them discover these mistakes.

**Comment by rkuhn** [comment]
Yes: I think we are in full agreement.
