### ISSUE TITLE
noAutoDestroy should seamlessly continue

### ISSUE THREAD

**Issue by rkuhn** [Actyx/machines#84]
Currently, the following code will block for the next live state:
```typescript
const machine = createMachineRunner(...)
await machine.peek()
for await (const state of machine.noAutoDestroy()) {
  ...
}
```
Instead, the state stored as a result of `peek()` should be immediately delivered.

Up for discussion: this method is useful for sharing a machine owned by a cache with the application, but it would be even easier if it returned a full machine instead of just the `next()` and `peek()` methods.

**Comment by Kelerchian** [comment]
#85 is only an additional test case that asserts this particular case
